import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "sonner";

import ConvexClientProvider from "@/components/convex-client-provider";

import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("dark flex items-stretch flex-col", inter.className)}>
        <Suspense fallback={"Loading..."}>
          <ConvexClientProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </ConvexClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
